[package]
name = "rawk-regex"
version = "0.1.0"
authors = ["Michael Howell <michael@notriddle.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex-syntax = "0.6.18"
regex = "1.3"
